### ISSUE TITLE
test example yields OSError

### ISSUE THREAD

**Issue by aleaf** [tenemark/mikecalsetup#3]
After installing mikecalsetup as directed in the readme, executing the tests from the tests folder with:
```
python -m unittest
```
produced this error:
```
OSError: [Errno 22] Invalid argument: 'example_models\\Karup\\Karup_Basic\\|.\\Model Inputs\\MIKE_SHE_vege.ETV|'
```

I also encountered this error when trying to run `example usage.ipynb` after installing `jupyter` and `notebook` as mentioned in #2.

**Comment by tenemark** [comment]
This specific path formatting issue that led to the OSError is due to the package not stripping the vertical lines from the string, when it should have. I have added an extra line to the script to avoid this error from happening again.
