### ISSUE TITLE
Documentation improvement: PEST example

### ISSUE THREAD

**Issue by aleaf** [tenemark/mikecalsetup#5]
The main readme file and JOSS paper state that mikecalsetup can produce input for PEST but `example usage.ipynb` only seems to illustrate and OSTRICH use case. It would be helpful to include a PEST example as well; this could also help users understand what the key differences are between mikecalsetup and [pyEMU](https://github.com/pypest/pyemu). Ideally this PEST example (and the existing OSTRICH example) would be complete working examples that include successful execution of a forward model run, to demonstrate that the input produced by mikecalsetup works as intended. These examples would also ideally be included in the automated testing and CI #7.

**Comment by tenemark** [comment]
As suggested, I have added some extra examples and moved them to the folder "examples". The examples now also include execution of a forward model run with PEST and OSTRICH. Also, an example (example_PEST_with_PstFrom.ipynb) shows how users of MIKE SHE can access the functionality of pyEMU and mikecalsetup at the same time.
