### ISSUE TITLE
Documentation improvement: HTML documentation

### ISSUE THREAD

**Issue by aleaf** [tenemark/mikecalsetup#6]
While it looks like most functions are classes are documented with numpy-style docstrings, I would highly encourage setting up HTML documentation. The [Scientific Python Cookiecutter](https://github.com/NSLS-II/scientific-python-cookiecutter) has an excellent template and guide to help you do this relatively quickly. This would not only automatically render the docstrings into an HTML API guide, but would also allow narrative documentation to be included, which would help users better understand the software. Regrettably, for reasons I don't understand, the CI portion of the Scientific Python Cookiecutter guide are focused on Travis, which has largely been dropped as the standard for open-source projects in favor of GitHub Actions. But, GitHub Actions can generally be readily set up (for automated testing and documentation publishing) by copying and pasting workflows from other projects (for example, you could copy the workflows from mikeio).

**Comment by tenemark** [comment]
This is a great idea and definitely something I will work on in the future. At this stage, I feel like the package is sufficiently documented by the examples and the numpy-style docstrings
